# WebSite settings
title: "麥克的筆記本"
email: mike2007.cv96g@gmail.com
description: "Full Stack Developer"
baseurl: "https://mike2014mike.github.io/"
url: "https://mike2014mike.github.io/"
title_description: "努力朝全端工程師邁進"
title_image: "./favicons/android-chrome-192x192.png"
google_analytics: "UA-122457148-1"
disqus_account: mikechen2018
github_repository: https://github.com/mike2014mike/mike2014mike.github.io
addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
twitter_username: SuperGeoMike
github_username:  mike2014mike
instagram_username: 
reddit_username: 
linkedin_link: https://www.linkedin.com/in/mike-chen-869602a4/
google_plus_link: https://plus.google.com/u/0/+%E9%99%B3%E5%86%A0%E5%AE%87mikechen
stackoverflow_link: 
xing_link:
facebook_link: https://www.facebook.com/mike.chen.731

# Footer
footer_left: "Maintained by <a href=\"https://github.com/mike2014mike\">Mike Chen</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/mike2014mike\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  # https://github.com/jekyll/jekyll/pull/4090
  syntax_highlighter: rouge
  # Rouge Highlighter in Kramdown › http://kramdown.gettalong.org/syntax_highlighter/rouge.html
  # span, block element options fall back to global
  syntax_highlighter_opts:
    default_lang: html
    # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: 'highlight'
    #line_numbers: true # bad idea, spans don't need linenos and would inherit this option
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

permalink: pretty
exclude: [vendor]
